"""empty message

Revision ID: 09351b0e1bbe
Revises: 5d21dd83d225
Create Date: 2021-11-17 20:18:49.020010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09351b0e1bbe'
down_revision = '5d21dd83d225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['ccnTipoId'], ['ccnTipoId'])
    op.drop_column('tblClientes', 'idMunicipio')
    op.drop_column('tblClientes', 'idRoles')
    op.drop_column('tblClientes', 'idPais')
    op.drop_column('tblClientes', 'idDepartamento')
    op.drop_column('tblClientes', 'fk_ccnEstado')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('fk_ccnEstado', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tblClientes', sa.Column('idDepartamento', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tblClientes', sa.Column('idPais', mysql.VARCHAR(length=2), nullable=False))
    op.add_column('tblClientes', sa.Column('idRoles', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('tblClientes', sa.Column('idMunicipio', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    # ### end Alembic commands ###
