"""empty message

Revision ID: 12c3a0a4ec9d
Revises: 4f51abca9daa
Create Date: 2021-11-17 20:00:15.872694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12c3a0a4ec9d'
down_revision = '4f51abca9daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['ccnTipoId'], ['ccnTipoId'])
    op.create_foreign_key(None, 'tblClientes', 'tblMunicipios', ['lugarExpIdCliente'], ['ccnMunicipios'])
    op.drop_column('tblClientes', 'idDepartamento')
    op.drop_column('tblClientes', 'fk_ccnEstado')
    op.drop_column('tblClientes', 'idMunicipio')
    op.drop_column('tblClientes', 'idRoles')
    op.drop_column('tblClientes', 'idPais')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('idPais', mysql.VARCHAR(length=2), nullable=False))
    op.add_column('tblClientes', sa.Column('idRoles', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('tblClientes', sa.Column('idMunicipio', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tblClientes', sa.Column('fk_ccnEstado', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tblClientes', sa.Column('idDepartamento', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    # ### end Alembic commands ###
