"""empty message

Revision ID: 208d8678dff3
Revises: 621ced605ecc
Create Date: 2021-10-21 21:33:38.666619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208d8678dff3'
down_revision = '621ced605ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblClaseTasaInteres',
    sa.Column('ccnClaseTasaInteres', sa.Integer(), nullable=False),
    sa.Column('claseTasaInteres', sa.String(length=1), nullable=True),
    sa.Column('descripcionClaseTasa', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('ccnClaseTasaInteres')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblClaseTasaInteres')
    # ### end Alembic commands ###
