"""empty message

Revision ID: 211d9b40989b
Revises: 40b7935a03a2
Create Date: 2021-10-23 01:16:10.169637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211d9b40989b'
down_revision = '40b7935a03a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblPagos',
    sa.Column('ccnPagos', sa.Integer(), nullable=False),
    sa.Column('fechaPagoConvenio', sa.DateTime(), nullable=False),
    sa.Column('depositoElectronicoOrigen', sa.BigInteger(), nullable=False),
    sa.Column('codigoConvenio', sa.Integer(), nullable=False),
    sa.Column('montoPago', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ccnPagos')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblPagos')
    # ### end Alembic commands ###
