"""empty message

Revision ID: 27412a6ea58a
Revises: d102fcc26b7d
Create Date: 2021-11-17 21:53:24.453419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27412a6ea58a'
down_revision = 'd102fcc26b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tblClientes_ibfk_3', 'tblClientes', type_='foreignkey')
    op.drop_constraint('tblClientes_ibfk_7', 'tblClientes', type_='foreignkey')
    op.create_foreign_key(None, 'tblClientes', 'tblMunicipios', ['ccnMunicipio'], ['idMunicipio'])
    op.create_foreign_key(None, 'tblClientes', 'tblMunicipios', ['lugarExpIdCliente'], ['idMunicipio'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.create_foreign_key('tblClientes_ibfk_7', 'tblClientes', 'tblMunicipios', ['lugarExpIdCliente'], ['ccnMunicipios'])
    op.create_foreign_key('tblClientes_ibfk_3', 'tblClientes', 'tblMunicipios', ['ccnMunicipio'], ['ccnMunicipios'])
    # ### end Alembic commands ###
