"""empty message

Revision ID: 2b1ba997d852
Revises: 2c394520cb1d
Create Date: 2021-11-15 20:39:03.687101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b1ba997d852'
down_revision = '2c394520cb1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblDepartamentos', sa.Column('ccnPais', sa.Integer(), nullable=False))
    op.drop_constraint('tblDepartamentos_ibfk_1', 'tblDepartamentos', type_='foreignkey')
    op.create_foreign_key(None, 'tblDepartamentos', 'tblPaises', ['ccnPais'], ['ccnPais'])
    op.drop_column('tblDepartamentos', 'idPais')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblDepartamentos', sa.Column('idPais', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tblDepartamentos', type_='foreignkey')
    op.create_foreign_key('tblDepartamentos_ibfk_1', 'tblDepartamentos', 'tblPaises', ['idPais'], ['ccnPais'])
    op.drop_column('tblDepartamentos', 'ccnPais')
    # ### end Alembic commands ###
