"""empty message

Revision ID: 2b85d0af4669
Revises: d99e0259cb0d
Create Date: 2021-11-15 22:14:47.470099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b85d0af4669'
down_revision = 'd99e0259cb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblMunicipios', 'idDepartamento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblMunicipios', sa.Column('idDepartamento', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
