"""empty message

Revision ID: 2b996706b943
Revises: d18f00c79713
Create Date: 2021-10-22 23:28:12.835986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b996706b943'
down_revision = 'd18f00c79713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblDepartamentos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblDepartamentos',
    sa.Column('idDepartamento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcionDepartamento', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('idPais', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('ccnDepartamento', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idDepartamento'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
