"""empty message

Revision ID: 2c150c9ffa03
Revises: 7240978bf784
Create Date: 2021-11-15 20:27:29.359650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c150c9ffa03'
down_revision = '7240978bf784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblClientes', 'tipoId')
    op.drop_column('tblClientes', 'fk_ccnTipoId')
    op.drop_column('tblClientes', 'ccnEstado')
    op.create_foreign_key(None, 'tblDepartamentos', 'tblPaises', ['idPais'], ['ccnPais'])
    op.add_column('tblTipoId', sa.Column('ccnTipoId', sa.Integer(), nullable=False))
    op.drop_column('tblTipoId', 'ccn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblTipoId', sa.Column('ccn', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('tblTipoId', 'ccnTipoId')
    op.drop_constraint(None, 'tblDepartamentos', type_='foreignkey')
    op.add_column('tblClientes', sa.Column('ccnEstado', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tblClientes', sa.Column('fk_ccnTipoId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tblClientes', sa.Column('tipoId', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
