"""empty message

Revision ID: 2c394520cb1d
Revises: 6412b9a96535
Create Date: 2021-11-15 20:36:13.087409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c394520cb1d'
down_revision = '6412b9a96535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblDepartamentos', sa.Column('idPais', sa.Integer(), nullable=False))
    op.drop_constraint('tblDepartamentos_ibfk_1', 'tblDepartamentos', type_='foreignkey')
    op.create_foreign_key(None, 'tblDepartamentos', 'tblPaises', ['idPais'], ['ccnPais'])
    op.drop_column('tblDepartamentos', 'ccnPais')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblDepartamentos', sa.Column('ccnPais', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tblDepartamentos', type_='foreignkey')
    op.create_foreign_key('tblDepartamentos_ibfk_1', 'tblDepartamentos', 'tblPaises', ['ccnPais'], ['ccnPais'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_column('tblDepartamentos', 'idPais')
    # ### end Alembic commands ###
