"""empty message

Revision ID: 2d7101727888
Revises: 9a8aaead4a61
Create Date: 2021-10-25 19:49:33.861095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7101727888'
down_revision = '9a8aaead4a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['tipoId'], ['ccn'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    # ### end Alembic commands ###
