"""empty message

Revision ID: 308789683b37
Revises: 
Create Date: 2021-10-20 23:00:38.739312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308789683b37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tblClientes', ['numeroIdCliente'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tblClientes', type_='unique')
    # ### end Alembic commands ###
