"""empty message

Revision ID: 357fa7146116
Revises: f659ee542b7d
Create Date: 2021-10-22 22:58:21.869999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357fa7146116'
down_revision = 'f659ee542b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblDepartamentos',
    sa.Column('idDepartamento', sa.Integer(), nullable=False),
    sa.Column('descripcionDepartamento', sa.String(length=50), nullable=False),
    sa.Column('idPais', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('idDepartamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblDepartamentos')
    # ### end Alembic commands ###
