"""empty message

Revision ID: 40b7935a03a2
Revises: b1964491bc9c
Create Date: 2021-10-23 00:55:23.627815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b7935a03a2'
down_revision = 'b1964491bc9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblMunicipios',
    sa.Column('ccnMunicipios', sa.Integer(), nullable=False),
    sa.Column('idMunicipio', sa.Integer(), nullable=False),
    sa.Column('descripcionMunicipio', sa.String(length=60), nullable=False),
    sa.Column('idDepartamento', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ccnMunicipios')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblMunicipios')
    # ### end Alembic commands ###
