"""empty message

Revision ID: 4a3da75aff37
Revises: 7aac1636d2cd
Create Date: 2021-10-21 21:08:43.910303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a3da75aff37'
down_revision = '7aac1636d2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('numeroIdEmpleado', table_name='tblEmpleados')
    op.drop_table('tblEmpleados')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblEmpleados',
    sa.Column('ccnEmpleado', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numeroIdEmpleado', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipoId', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('fechaExpIdEmpleado', sa.DATE(), nullable=False),
    sa.Column('lugarExpIdEmpleado', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('primerNombreEmpleado', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('segundoNombreEmpleado', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('primerApellidoEmpleado', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('segundoApellidoEmpleado', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fechaNacimientoEmpleado', sa.DATE(), nullable=False),
    sa.Column('idEstado', mysql.VARCHAR(length=1), nullable=False),
    sa.Column('idRoles', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('direccionEmpleado', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('barrioEmpleado', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('idPais', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('idDepartamento', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idMunicipio', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('celularEmpleado', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('correoElectronicoEmpleado', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contraseñaEmpleado', mysql.VARCHAR(length=300), nullable=False),
    sa.PrimaryKeyConstraint('ccnEmpleado'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('numeroIdEmpleado', 'tblEmpleados', ['numeroIdEmpleado'], unique=False)
    # ### end Alembic commands ###
