"""empty message

Revision ID: 4f51abca9daa
Revises: 0b0b0da64172
Create Date: 2021-11-17 19:56:18.301605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f51abca9daa'
down_revision = '0b0b0da64172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['ccnTipoId'], ['ccnTipoId'])
    op.create_foreign_key(None, 'tblClientes', 'tblMunicipios', ['lugarExpIdCliente'], ['ccnMunicipios'])
    op.drop_column('tblClientes', 'idRoles')
    op.drop_column('tblClientes', 'idMunicipio')
    op.drop_column('tblClientes', 'idDepartamento')
    op.drop_column('tblClientes', 'fk_ccnEstado')
    op.drop_column('tblClientes', 'idPais')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('idPais', mysql.VARCHAR(length=2), nullable=False))
    op.add_column('tblClientes', sa.Column('fk_ccnEstado', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tblClientes', sa.Column('idDepartamento', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tblClientes', sa.Column('idMunicipio', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tblClientes', sa.Column('idRoles', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    # ### end Alembic commands ###
