"""empty message

Revision ID: 575a42f1d406
Revises: df73f136cc07
Create Date: 2021-10-22 23:53:14.057237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575a42f1d406'
down_revision = 'df73f136cc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblDepositosInscritos',
    sa.Column('ccnDepositosInscritos', sa.Integer(), nullable=False),
    sa.Column('filtroLista', sa.String(length=60), nullable=False),
    sa.Column('tipoDeposito', sa.String(length=5), nullable=True),
    sa.Column('depositoElectronico', sa.BigInteger(), nullable=False),
    sa.Column('nombrePersonalizado', sa.String(length=100), nullable=True),
    sa.Column('tipoId', sa.String(length=2), nullable=False),
    sa.Column('numeroIdCliente', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ccnDepositosInscritos')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblDepositosInscritos')
    # ### end Alembic commands ###
