"""empty message

Revision ID: 63dc97521561
Revises: 9def38b067ce
Create Date: 2021-10-25 19:55:40.638690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63dc97521561'
down_revision = '9def38b067ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['tipoId'], ['ccn'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    # ### end Alembic commands ###
