"""empty message

Revision ID: 6412b9a96535
Revises: 2c150c9ffa03
Create Date: 2021-11-15 20:34:45.770206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6412b9a96535'
down_revision = '2c150c9ffa03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblDepartamentos', sa.Column('idPais', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tblDepartamentos', 'tblPaises', ['idPais'], ['ccnPais'])
    op.drop_column('tblDepartamentos', 'ccnPais')
    op.add_column('tblTipoId', sa.Column('ccnTipoId', sa.Integer(), nullable=False))
    op.drop_column('tblTipoId', 'ccn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblTipoId', sa.Column('ccn', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('tblTipoId', 'ccnTipoId')
    op.add_column('tblDepartamentos', sa.Column('ccnPais', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tblDepartamentos', type_='foreignkey')
    op.drop_column('tblDepartamentos', 'idPais')
    # ### end Alembic commands ###
