"""empty message

Revision ID: 7240978bf784
Revises: a8dc29b5f1e5
Create Date: 2021-11-15 20:26:04.970566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7240978bf784'
down_revision = 'a8dc29b5f1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tblClientes', 'ccnTipoId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('tblClientes', 'ccnEstado')
    op.drop_column('tblClientes', 'fk_ccnTipoId')
    op.drop_column('tblClientes', 'tipoId')
    op.create_foreign_key(None, 'tblDepartamentos', 'tblPaises', ['idPais'], ['ccnPais'])
    op.add_column('tblTipoId', sa.Column('ccnTipoId', sa.Integer(), nullable=False))
    op.drop_column('tblTipoId', 'ccn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblTipoId', sa.Column('ccn', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('tblTipoId', 'ccnTipoId')
    op.drop_constraint(None, 'tblDepartamentos', type_='foreignkey')
    op.add_column('tblClientes', sa.Column('tipoId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tblClientes', sa.Column('fk_ccnTipoId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tblClientes', sa.Column('ccnEstado', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('tblClientes', 'ccnTipoId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
