"""empty message

Revision ID: 7479f8f79d06
Revises: 63b2f515bd10
Create Date: 2021-11-17 20:10:11.984378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7479f8f79d06'
down_revision = '63b2f515bd10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tblClientes', 'tblMunicipios', ['lugarExpIdCliente'], ['ccnMunicipios'])
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['ccnTipoId'], ['ccnTipoId'])
    op.drop_column('tblClientes', 'idPais')
    op.drop_column('tblClientes', 'idDepartamento')
    op.drop_column('tblClientes', 'idMunicipio')
    op.drop_column('tblClientes', 'fk_ccnEstado')
    op.drop_column('tblClientes', 'idRoles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('idRoles', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('tblClientes', sa.Column('fk_ccnEstado', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tblClientes', sa.Column('idMunicipio', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tblClientes', sa.Column('idDepartamento', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tblClientes', sa.Column('idPais', mysql.VARCHAR(length=2), nullable=False))
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    # ### end Alembic commands ###
