"""empty message

Revision ID: 7aac1636d2cd
Revises: fc0bcd10ebf7
Create Date: 2021-10-21 21:06:09.045642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aac1636d2cd'
down_revision = 'fc0bcd10ebf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblDepositosElectronicos',
    sa.Column('ccnDepositoElectronico', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ccnDepositoElectronico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblDepositosElectronicos')
    # ### end Alembic commands ###
