"""empty message

Revision ID: 82f435a09d3c
Revises: a9a983d8ad3a
Create Date: 2021-10-22 22:09:38.416669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f435a09d3c'
down_revision = 'a9a983d8ad3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblConvenios',
    sa.Column('ccnConvenios', sa.Integer(), nullable=False),
    sa.Column('codigoConvenio', sa.Integer(), nullable=False),
    sa.Column('nombreEmpresa', sa.String(length=100), nullable=False),
    sa.Column('convenio', sa.String(length=100), nullable=False),
    sa.Column('datoCaptura', sa.String(length=100), nullable=False),
    sa.Column('modalidadConvenio', sa.String(length=100), nullable=False),
    sa.Column('idMunicipio', sa.Integer(), nullable=False),
    sa.Column('idDepartamento', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ccnConvenios')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblConvenios')
    # ### end Alembic commands ###
