"""empty message

Revision ID: 8e4964a85a45
Revises: 2b85d0af4669
Create Date: 2021-11-17 19:51:59.913796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e4964a85a45'
down_revision = '2b85d0af4669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('ccnEstado', sa.Integer(), nullable=True))
    op.add_column('tblClientes', sa.Column('ccnRoles', sa.Integer(), nullable=True))
    op.add_column('tblClientes', sa.Column('ccnPais', sa.Integer(), nullable=True))
    op.add_column('tblClientes', sa.Column('ccnDepartamento', sa.Integer(), nullable=True))
    op.add_column('tblClientes', sa.Column('ccnMunicipio', sa.Integer(), nullable=True))
    op.alter_column('tblClientes', 'ccnTipoId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('tblClientes_ibfk_1', 'tblClientes', type_='foreignkey')
    op.create_foreign_key(None, 'tblClientes', 'tblEstados', ['ccnEstado'], ['ccnEstado'])
    op.create_foreign_key(None, 'tblClientes', 'tblMunicipios', ['lugarExpIdCliente'], ['ccnMunicipios'])
    op.create_foreign_key(None, 'tblClientes', 'tblPaises', ['ccnPais'], ['ccnPais'])
    op.create_foreign_key(None, 'tblClientes', 'tblMunicipios', ['ccnMunicipio'], ['ccnMunicipios'])
    op.create_foreign_key(None, 'tblClientes', 'tblRoles', ['ccnRoles'], ['ccnRoles'])
    op.create_foreign_key(None, 'tblClientes', 'tblDepartamentos', ['ccnDepartamento'], ['ccnDepartamento'])
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['ccnTipoId'], ['ccnTipoId'])
    op.drop_column('tblClientes', 'idRoles')
    op.drop_column('tblClientes', 'idMunicipio')
    op.drop_column('tblClientes', 'fk_ccnEstado')
    op.drop_column('tblClientes', 'idPais')
    op.drop_column('tblClientes', 'idDepartamento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('idDepartamento', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tblClientes', sa.Column('idPais', mysql.VARCHAR(length=2), nullable=False))
    op.add_column('tblClientes', sa.Column('fk_ccnEstado', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tblClientes', sa.Column('idMunicipio', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tblClientes', sa.Column('idRoles', mysql.VARCHAR(length=10), nullable=True))
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.create_foreign_key('tblClientes_ibfk_1', 'tblClientes', 'tblEstados', ['fk_ccnEstado'], ['ccnEstado'])
    op.alter_column('tblClientes', 'ccnTipoId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('tblClientes', 'ccnMunicipio')
    op.drop_column('tblClientes', 'ccnDepartamento')
    op.drop_column('tblClientes', 'ccnPais')
    op.drop_column('tblClientes', 'ccnRoles')
    op.drop_column('tblClientes', 'ccnEstado')
    # ### end Alembic commands ###
