"""empty message

Revision ID: 91683ae41ce6
Revises: 1b563fb3b544
Create Date: 2021-11-17 20:32:25.546173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91683ae41ce6'
down_revision = '1b563fb3b544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('ccnTipoId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['ccnTipoId'], ['ccnTipoId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_column('tblClientes', 'ccnTipoId')
    # ### end Alembic commands ###
