"""empty message

Revision ID: 9522af8981b0
Revises: eda380425b30
Create Date: 2021-10-25 23:12:47.782166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9522af8981b0'
down_revision = 'eda380425b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['ccn_Id'], ['ccn'])
    op.drop_column('tblClientes', 'tipoId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('tipoId', mysql.VARCHAR(length=2), nullable=False))
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    # ### end Alembic commands ###
