"""empty message

Revision ID: 9def38b067ce
Revises: 2d7101727888
Create Date: 2021-10-25 19:53:04.239648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9def38b067ce'
down_revision = '2d7101727888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tblClientes', 'tipoId',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['tipoId'], ['ccn'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.alter_column('tblClientes', 'tipoId',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###
