"""empty message

Revision ID: a4a645c08541
Revises: 211d9b40989b
Create Date: 2021-10-23 01:26:48.520628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a645c08541'
down_revision = '211d9b40989b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblPaises',
    sa.Column('ccnPais', sa.Integer(), nullable=False),
    sa.Column('idPais', sa.String(length=2), nullable=False),
    sa.Column('descripcionPais', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('ccnPais')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblPaises')
    # ### end Alembic commands ###
