"""empty message

Revision ID: a6f0d84814d1
Revises: 4882aa46781f
Create Date: 2021-10-26 01:16:33.007855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6f0d84814d1'
down_revision = '4882aa46781f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('tipoId', sa.Integer(), nullable=True))
    op.drop_constraint('tblClientes_ibfk_1', 'tblClientes', type_='foreignkey')
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['tipoId'], ['ccn'])
    op.drop_column('tblClientes', 'ccn_tipoId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('ccn_tipoId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.create_foreign_key('tblClientes_ibfk_1', 'tblClientes', 'tblTipoId', ['ccn_tipoId'], ['ccn'])
    op.drop_column('tblClientes', 'tipoId')
    # ### end Alembic commands ###
