"""empty message

Revision ID: a94d929da7a8
Revises: cc771aaddca4
Create Date: 2021-10-23 02:08:15.389226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94d929da7a8'
down_revision = 'cc771aaddca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblRoles',
    sa.Column('ccnRoles', sa.Integer(), nullable=False),
    sa.Column('idRoles', sa.String(length=7), nullable=False),
    sa.Column('descripcionRoles', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('ccnRoles')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblRoles')
    # ### end Alembic commands ###
