"""empty message

Revision ID: b39545ccbd95
Revises: fc69bfefc7b4
Create Date: 2021-10-23 02:35:58.410682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39545ccbd95'
down_revision = 'fc69bfefc7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblTransferencias',
    sa.Column('ccnTransferencia', sa.Integer(), nullable=False),
    sa.Column('fechaTransferencia', sa.DateTime(), nullable=False),
    sa.Column('depositoElectronicoOrigen', sa.BigInteger(), nullable=False),
    sa.Column('depositoElectronicoDestino', sa.BigInteger(), nullable=False),
    sa.Column('montoTransferencia', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ccnTransferencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblTransferencias')
    # ### end Alembic commands ###
