"""empty message

Revision ID: b58a0ec803e7
Revises: 575a42f1d406
Create Date: 2021-10-22 23:55:36.567456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b58a0ec803e7'
down_revision = '575a42f1d406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tblDepositosInscritos', 'tipoDeposito',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
    op.alter_column('tblDepositosInscritos', 'nombrePersonalizado',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tblDepositosInscritos', 'nombrePersonalizado',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tblDepositosInscritos', 'tipoDeposito',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
    # ### end Alembic commands ###
