"""empty message

Revision ID: b5c9cfaa2248
Revises: cb7714f5b274
Create Date: 2021-11-12 01:52:44.926324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5c9cfaa2248'
down_revision = 'cb7714f5b274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tblClientes', 'tipoId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tblClientes', 'idEstado',
               existing_type=mysql.VARCHAR(length=1),
               nullable=True)
    op.create_foreign_key(None, 'tblClientes', 'tblEstados', ['idEstado'], ['ccnEstado'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.alter_column('tblClientes', 'idEstado',
               existing_type=mysql.VARCHAR(length=1),
               nullable=False)
    op.alter_column('tblClientes', 'tipoId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
