"""empty message

Revision ID: b7a739b633a9
Revises: 79ee6073fa58
Create Date: 2021-11-12 02:38:00.151796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7a739b633a9'
down_revision = '79ee6073fa58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('fk_ccnTipoId', sa.Integer(), nullable=True))
    op.add_column('tblClientes', sa.Column('fk_ccnEstado', sa.Integer(), nullable=True))
    op.drop_constraint('tblClientes_ibfk_2', 'tblClientes', type_='foreignkey')
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['fk_ccnTipoId'], ['ccnTipoId'])
    op.create_foreign_key(None, 'tblClientes', 'tblEstados', ['fk_ccnEstado'], ['ccnEstado'])
    op.drop_column('tblClientes', 'ccnTipoId')
    op.drop_column('tblClientes', 'ccnEstado')
    op.drop_column('tblClientes', 'tipoId')
    op.add_column('tblTipoId', sa.Column('ccnTipoId', sa.Integer(), nullable=False))
    op.drop_column('tblTipoId', 'ccn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblTipoId', sa.Column('ccn', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('tblTipoId', 'ccnTipoId')
    op.add_column('tblClientes', sa.Column('tipoId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tblClientes', sa.Column('ccnEstado', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tblClientes', sa.Column('ccnTipoId', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.create_foreign_key('tblClientes_ibfk_2', 'tblClientes', 'tblEstados', ['ccnEstado'], ['ccnEstado'])
    op.drop_column('tblClientes', 'fk_ccnEstado')
    op.drop_column('tblClientes', 'fk_ccnTipoId')
    # ### end Alembic commands ###
