"""empty message

Revision ID: bfed5520a4ed
Revises: 7f66d1f7f4e3
Create Date: 2021-10-24 18:00:38.590697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfed5520a4ed'
down_revision = '7f66d1f7f4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblTipoId', 'ccnTipoDeposito')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblTipoId', sa.Column('ccnTipoDeposito', mysql.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
