"""empty message

Revision ID: c3e9357c2736
Revises: 9522af8981b0
Create Date: 2021-10-25 23:20:14.958001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3e9357c2736'
down_revision = '9522af8981b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tblClientes_ibfk_1', 'tblClientes', type_='foreignkey')
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['tipoId'], ['tipoId'])
    op.drop_column('tblClientes', 'ccn_Id')
    op.drop_column('tblTipoId', 'ccn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblTipoId', sa.Column('ccn', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('tblClientes', sa.Column('ccn_Id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.create_foreign_key('tblClientes_ibfk_1', 'tblClientes', 'tblTipoId', ['ccn_Id'], ['ccn'])
    # ### end Alembic commands ###
