"""empty message

Revision ID: cb7714f5b274
Revises: a6f0d84814d1
Create Date: 2021-10-26 01:59:02.327515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb7714f5b274'
down_revision = 'a6f0d84814d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tblClientes', 'tipoId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tblClientes', 'tipoId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
