"""empty message

Revision ID: cc771aaddca4
Revises: a4a645c08541
Create Date: 2021-10-23 02:03:21.019756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc771aaddca4'
down_revision = 'a4a645c08541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblPUC',
    sa.Column('ccnPUC', sa.Integer(), nullable=False),
    sa.Column('codigoCuenta', sa.Integer(), nullable=False),
    sa.Column('nombreCuenta', sa.String(length=100), nullable=False),
    sa.Column('naturalezaCuenta', sa.String(length=1), nullable=False),
    sa.Column('tipoCuenta', sa.String(length=3), nullable=False),
    sa.Column('nivelCuenta', sa.String(length=60), nullable=False),
    sa.Column('lineaCuenta', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ccnPUC')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblPUC')
    # ### end Alembic commands ###
