"""empty message

Revision ID: d18f00c79713
Revises: 357fa7146116
Create Date: 2021-10-22 23:03:35.851267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18f00c79713'
down_revision = '357fa7146116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblDepartamentos', sa.Column('ccnDepartamento', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblDepartamentos', 'ccnDepartamento')
    # ### end Alembic commands ###
