"""empty message

Revision ID: df73f136cc07
Revises: 2b996706b943
Create Date: 2021-10-22 23:29:08.241477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df73f136cc07'
down_revision = '2b996706b943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblDepartamentos',
    sa.Column('ccnDepartamento', sa.Integer(), nullable=False),
    sa.Column('idDepartamento', sa.Integer(), nullable=False),
    sa.Column('descripcionDepartamento', sa.String(length=60), nullable=False),
    sa.Column('idPais', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('ccnDepartamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblDepartamentos')
    # ### end Alembic commands ###
