"""empty message

Revision ID: ec6274297c98
Revises: 4437bad9df01
Create Date: 2021-10-25 23:30:39.617771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec6274297c98'
down_revision = '4437bad9df01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('ccn_tipoId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['ccn_tipoId'], ['ccn'])
    op.drop_column('tblClientes', 'ccn_Id')
    op.drop_column('tblClientes', 'tipoId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('tipoId', mysql.VARCHAR(length=2), nullable=True))
    op.add_column('tblClientes', sa.Column('ccn_Id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    op.drop_column('tblClientes', 'ccn_tipoId')
    # ### end Alembic commands ###
