"""empty message

Revision ID: eda380425b30
Revises: 9384e75088c3
Create Date: 2021-10-25 22:47:57.004718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eda380425b30'
down_revision = '9384e75088c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tblClientes', 'tblTipoId', ['ccn_Id'], ['ccn'])
    op.drop_column('tblClientes', 'tipoId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblClientes', sa.Column('tipoId', mysql.VARCHAR(length=2), nullable=False))
    op.drop_constraint(None, 'tblClientes', type_='foreignkey')
    # ### end Alembic commands ###
