"""empty message

Revision ID: f659ee542b7d
Revises: 82f435a09d3c
Create Date: 2021-10-22 22:48:45.690009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f659ee542b7d'
down_revision = '82f435a09d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblConveniosInscritos',
    sa.Column('ccnConveniosInscritos', sa.Integer(), nullable=False),
    sa.Column('filtroLista', sa.String(length=50), nullable=False),
    sa.Column('codigoConvenio', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ccnConveniosInscritos')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblConveniosInscritos')
    # ### end Alembic commands ###
