"""empty message

Revision ID: fc0bcd10ebf7
Revises: 308789683b37
Create Date: 2021-10-21 20:44:08.171278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0bcd10ebf7'
down_revision = '308789683b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblEmpleados',
    sa.Column('ccnEmpleado', sa.Integer(), nullable=False),
    sa.Column('numeroIdEmpleado', sa.Integer(), nullable=False),
    sa.Column('tipoId', sa.String(length=2), nullable=False),
    sa.Column('fechaExpIdEmpleado', sa.Date(), nullable=False),
    sa.Column('lugarExpIdEmpleado', sa.Integer(), nullable=False),
    sa.Column('primerNombreEmpleado', sa.String(length=20), nullable=False),
    sa.Column('segundoNombreEmpleado', sa.String(length=20), nullable=True),
    sa.Column('primerApellidoEmpleado', sa.String(length=20), nullable=False),
    sa.Column('segundoApellidoEmpleado', sa.String(length=20), nullable=True),
    sa.Column('fechaNacimientoEmpleado', sa.Date(), nullable=False),
    sa.Column('idEstado', sa.String(length=1), nullable=False),
    sa.Column('idRoles', sa.String(length=10), nullable=True),
    sa.Column('direccionEmpleado', sa.String(length=60), nullable=False),
    sa.Column('barrioEmpleado', sa.String(length=60), nullable=False),
    sa.Column('idPais', sa.String(length=2), nullable=False),
    sa.Column('idDepartamento', sa.Integer(), nullable=False),
    sa.Column('idMunicipio', sa.Integer(), nullable=False),
    sa.Column('celularEmpleado', sa.BigInteger(), nullable=False),
    sa.Column('correoElectronicoEmpleado', sa.String(length=100), nullable=False),
    sa.Column('contraseñaEmpleado', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('ccnEmpleado'),
    sa.UniqueConstraint('numeroIdEmpleado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblEmpleados')
    # ### end Alembic commands ###
