"""empty message

Revision ID: fc69bfefc7b4
Revises: 3c338aa079e3
Create Date: 2021-10-23 02:25:59.985749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc69bfefc7b4'
down_revision = '3c338aa079e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblTipoId',
    sa.Column('ccnTipoDeposito', sa.Integer(), nullable=False),
    sa.Column('tipoId', sa.String(length=2), nullable=False),
    sa.Column('descripcionTipoId', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ccnTipoDeposito')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblTipoId')
    # ### end Alembic commands ###
